### ISSUE TITLE
Adding a favicon to the website

### ISSUE THREAD

**Issue by Aloneduckling** [dsc-iem/WebDev-Hacktoberfest#4]
Hello,
I thought it would be nice if the website has a favicon for the looks of the website.
How about this image
https://ibb.co/XW4195b

**Comment by Aloneduckling** [comment]
I will do this if you approve.

**Comment by Ninjavin** [comment]
Great @Aloneduckling . I am assigning this issue to you. Use this for favicon https://drive.google.com/file/d/1leycxVEEHgYZJP3h5v6DSkX7IloilMem/view?usp=sharing

**Comment by Aloneduckling** [comment]
just asking, are you a lead of your DSC

**Comment by Ninjavin** [comment]
Nope. @mahakmakharia is. I am leading the Web-Team for 2020.

**Comment by Aloneduckling** [comment]
Ok cool!
One more thing. If I want to join your club what will be the requirements

**Comment by Ninjavin** [comment]
You can join if your college doesn't have a DSC.

**Comment by Aloneduckling** [comment]
Ok cool! My college does not have a DSC. Can you share me the link so that I can join you DSC

**Comment by Ninjavin** [comment]
Fill this form for registering : bit.ly/dsciem2020

**Comment by Aloneduckling** [comment]
Hey, thanks for the link. Turns out my friend's college has a DSC so I am thinking to join that. Sorry for the trouble from my side

**Comment by kanishk7559** [comment]
is this issue is still open ? if yes please assign it to me i will do it
