### ISSUE TITLE
Add your profile card

### ISSUE THREAD

**Issue by Ninjavin** [dsc-iem/WebDev-Hacktoberfest#6]
https://dsc-iem.github.io/WebDev-Hacktoberfest is the website for this repository. Add your own profile card in the Website, the `README.md` will guide you through the process. 
Anyone can work on this issue without being assigned. 
Feel free to ask any queries in the comments.

**Comment by Swarnim01** [comment]
Hey! @Ninjavin I'll go with this issue(Not-issue) and will add my card....Do let me know if you want to add anything else to enhance your website...i'll make a PR after 1 Oct.

**Comment by illegalcall** [comment]
Hey,guess I am 3 minutes late..No problems, if you make any new issues, I'll be happy to contribute.

**Comment by BAAHUBALI7781** [comment]
I would be happy to contribute in anything you want to add in your website.

**Comment by Ninjavin** [comment]
@Swarnim01 You are free to look for enhancements in the Website and open an issue. Meanwhile if I find something worth adding, I will definitely create an issue.
Also @illegalcall  doesn't matter. More the profile cards, the merrier. Any number of people can contribute to this issue, and that's why I am not assigning this to any individual.

**Comment by Ninjavin** [comment]
@BAAHUBALI7781 Great! :+1:

**Comment by sandipanpanda** [comment]
Thanks a lot @Ninjavin . Its a great initiative for the people new to open source. I would love to contribute to this issue.

**Comment by rishavjaiss** [comment]
Hi, I'll take this!

**Comment by Ankitz007** [comment]
Can multiple people work on this?

**Comment by Ninjavin** [comment]
@Ankitz007 Yes!

**Comment by illegalcall** [comment]
@Ninjavin Thank You so much

**Comment by Aman-Jamshed** [comment]
Hey! @Ninjavin...I would like to work on this!!

**Comment by ayushgaur03** [comment]
hey! @Ninjavin I would also be adding my profile card.

**Comment by NirajSrivastava18** [comment]
I am also adding my profile card.

**Comment by Aman-Jamshed** [comment]
Please review my PR #22

**Comment by Aman-Jamshed** [comment]
@Ninjavin Please review my PR #22

**Comment by Swarnim01** [comment]
@Ninjavin  why our PR says-
Your PR was submitted to a repository that we've excluded from Hacktoberfest as it doesn't align with our core values.

the issue has hactoberfest2020 tag...then why so?

**Comment by Aman-Jamshed** [comment]
Yes...I am also facing the same issue! @Ninjavin  Can you please tell us why?

**Comment by ommiy2j** [comment]
hey @Ninjavin I would also be adding my profile card...

**Comment by Ninjavin** [comment]
@Swarnim01 @Aman-Jamshed Yes. And I am really sorry for the inconvenience. I am not sure about the reason though, maybe because it didn't align well with the Hacktoberfest guidelines. I am looking into the matter. Meanwhile try and contribute to other open-source repositories. I apologize again for the trouble.

**Comment by Swarnim01** [comment]
Not a problem at all @Ninjavin .....At least i learned to make PR  ..Thanks for the making this issue to work on.
Will you be merging them??
